//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetting
    {
        public int AppSettingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> TaxPercent { get; set; }
        public string Currency { get; set; }
        public Nullable<double> DeliveryCharges { get; set; }
        public string TopHeadDescription { get; set; }
        public Nullable<double> MinOrderAmount { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
