//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer1
    {
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> IsSms { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> RedeemPoints { get; set; }
        public Nullable<decimal> CurrentPoint { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
