//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public Nullable<int> ExpenseTypeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Date { get; set; }
        public string Reason { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual Location Location { get; set; }
    }
}
