//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashSaleDetail
    {
        public int FlashSaleDetailID { get; set; }
        public Nullable<int> FlashSaleID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
    
        public virtual FlashSale FlashSale { get; set; }
    }
}
